from mammal import Mammal
class Platypus(Mammal):
    def __init__(self, name:str, species:str, hair_color:str, eggs: int):
        super(). __init__
        self.eggs = eggs

def lay_eggs(self):
    self.eggs += 1
if __name__ == '__main__':
    perry = Platypus('Perry', 'platypus', 'green', 0)
    perry.eat('salad')
    perry.sleep()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   